# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculatescore.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QInputDialog, QMessageBox
import sqlite3


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 400)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(25, -1, 25, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.cb0 = QtWidgets.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.cb0.setFont(font)
        self.cb0.setObjectName("cb0")
        self.horizontalLayout.addWidget(self.cb0)
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cb1 = QtWidgets.QComboBox(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.cb1.setFont(font)
        self.cb1.setObjectName("cb1")
        self.cb1.addItem("")
        self.horizontalLayout.addWidget(self.cb1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line = QtWidgets.QFrame(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.label_4 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.line_2 = QtWidgets.QFrame(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lw1 = QtWidgets.QListWidget(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lw1.setFont(font)
        self.lw1.setObjectName("lw1")
        self.horizontalLayout_2.addWidget(self.lw1)
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.lw2 = QtWidgets.QListWidget(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lw2.setFont(font)
        self.lw2.setObjectName("lw2")
        self.horizontalLayout_2.addWidget(self.lw2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.line_3 = QtWidgets.QFrame(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.scorelabel = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.scorelabel.setFont(font)
        self.scorelabel.setObjectName("scorelabel")
        self.horizontalLayout_3.addWidget(self.scorelabel)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.pushButton.clicked.connect(self.evalute)
        self.load_dropdowns()
        self.cb0.currentIndexChanged.connect(self.evalute)
        self.cb1.currentIndexChanged.connect(self.evalute)

        #self.SelectTeam.currentIndexChanged.connect(self.evalute)
        #self.comboBox.currentIndexChanged.connect(self.evalute)   # re-run evaluate when match changes

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

       

    def load_dropdowns(self):
        conn = sqlite3.connect(r"D:\pythonfinal\fantasy")
        cur = conn.cursor()

        self.cb0.clear()
        cur.execute("SELECT DISTINCT name FROM teams")
        teams = [r[0] for r in cur.fetchall()]
        self.cb0.addItems(teams)

        self.cb1.clear()
        cur.execute("SELECT name FROM sqlite_master WHERE type='table'")
        tables = [r[0] for r in cur.fetchall() if r[0] not in ("teams", "stats")]
        self.cb1.addItems(tables)

        conn.close()

    def evalute(self):
        try:
            conn = sqlite3.connect(r"D:\pythonfinal\fantasy")
            team = self.cb0.currentText()
            match = self.cb1.currentText()

            self.lw1.clear()
            self.lw2.clear()

            if not team or not match:
                self.scorelable.setText("0")
                return
            

            sql1 = "SELECT players, value FROM teams WHERE name=?"
            cur = conn.execute(sql1, (team,))
            rows = cur.fetchall()

            if not rows:
                self.scorelabel.setText("0")
                conn.close()
                return

            teamttl = 0
            players = rows[0][0].split(",")
            for nm in players:
                self.lw1.addItem(nm)

                cursor = conn.execute(f"SELECT * from {match} WHERE player=?", (nm,))
                row = cursor.fetchone()
                if not row:
                    self.lw2.addItem("0")
                    continue
                
                #batting score
                batscore = int(row[1] / 2)
                if row[1] >= 50: batscore += 5
                if row[1] >= 100: batscore += 10
                if row[1] > 0:
                    sr = row[1] / row[2]
                    if 80 <= sr < 100: batscore += 2
                    if sr >= 100: batscore += 4
                batscore += row[3] + 2 * row[4]

                bowlscore = row[8] * 10
                if row[8] >= 3: bowlscore += 5
                if row[8] >= 5: bowlscore += 10
                if row[7] > 0:
                    er = 6 * row[7] / row[5]
                    if er <= 2: bowlscore += 10
                    elif er <= 3.5: bowlscore += 7
                    elif er <= 4.5: bowlscore += 4

                fieldscore = (row[9] + row[10] + row[11]) * 10
                ttl = batscore + bowlscore + fieldscore
                
                self.lw2.addItem(str(ttl))
                teamttl += ttl

            self.scorelabel.setText(str(teamttl))
        except Exception as e:
            self.scorelabel.setText(f"Error: {e}")
        finally:
            try:
                conn.close()
            except:
                pass


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Choose Team"))
        self.label.setText(_translate("Dialog", "Choose Match"))
        self.cb1.setItemText(0, _translate("Dialog", "Match1"))
        self.label_5.setText(_translate("Dialog", "Players"))
        self.label_4.setText(_translate("Dialog", "Score"))
        self.pushButton.setText(_translate("Dialog", "Evaluate Score"))
        self.scorelabel.setText(_translate("Dialog", "00"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
